### ISSUE TITLE
Supported Versions of Dependencies

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#28]
We should consider the versions of the dependencies we support, specify them and test at least the bounds in our tests.
For example, we maybe want to use
 - pytorch>=2.0,<3.0 (our tests should test 2.0.0 and latest)
 - numpy>=1.20 (??  numpy typing was introduced at 1.20 I believe)
 
 etc.
 This is not urgent, and should be reevaluated from time to time

**Comment by fzimmermann89** [comment]
Especially if we want to depend on pulseq (#78), we have to track which versions are compatible and what features we can use.

**Comment by fzimmermann89** [comment]
we now limit xsd as ismrmrd python has a bug in there dependencies.
we will have to remove this later on!

**Comment by ckolbPTB** [comment]
utilise e.g. https://pypi.org/project/pessimist/ to check requirements. 

run once every week as an github action?

**Comment by ckolbPTB** [comment]
maybe we could also enable automatic update PRs:

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

**Comment by schuenke** [comment]
I just set up dependabot version updates for all python packages and all gh actions for the [BMCTool Repo](https://github.com/schuenke/BMCTool). A simple config that allready groups the updates into single PR for each package ecosystem looks like this:

```yaml
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  groups:
    python-packages:
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    all-actions:
      patterns: [ "*" ]

```

This is how an example PR looks like: https://github.com/schuenke/BMCTool/pull/31


NOTE: for the coverage report to work also in the dependabot PRs, we have to add the GIST secret to the dependabot secrets as well. Probably need to create a new token, if @ckolbPTB didn't save it somewhere. But it's done in a minute.
