### ISSUE TITLE
homogenize delayed annotation evaluation in all files

### ISSUE THREAD

**Issue by fzimmermann89** [PTB-MR/mrpro#311]
Might be useful for consistency to always  `from __future__ import annotations`

This can be done using ruff:

```
[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
```
@schuenke : what do you think?

..or only do it when it is really required. currently, we do it in a lot of random files.

**Comment by schuenke** [comment]
do we still need it when we use the `from typing import Self` style?

**Comment by fzimmermann89** [comment]
..or remove them from all files and see where we actually need them.

**Comment by schuenke** [comment]
If we switch to the `from typing import Self` annotation style, we might need to specify that the mypy pre-commit hook uses a python version >=3.11. This was an Issue for me in another repo... this is how the pre-commit config might need to look like:

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        pass_filenames: false
        always_run: true
        args: [src, tests, examples, --python-version=3.11]
```
