### ISSUE TITLE
Pre-commit on changed notebooks

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#613]
If I understand it correctly then currently the different github workflows run in parallel. This can mean that the notebooks are run before the pre-commit ensures that they are up-to-date. This means it needs a few rounds of triggering pre-commit.ci to ensure the updated notebooks are run. Maybe we should in general ensure that all the workflows are only run after the pre-commit.ci has finished. Dependency on other workflows can be achieved with e.g.
```
on:
  workflow_run:
    workflows: ["pre-commit.ci"]
    types:
      - completed
```
